# EdgeOne.ai Functions 配置文件
name = "bmnr-tracker"
compatibility_date = "2024-01-01"
node_compat = true

# 环境变量
[env.production.vars]
TARGET_URL = "https://trackbmnr.com"
NODE_ENV = "production"

# 路由配置
[[routes]]
pattern = "*"
zone_name = "your-domain.com" # 请替换为您的域名